apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: incidentcad.com
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: dylan@incidentcad.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: incidentcad.com
    # Enable the HTTP-01 challenge provider
    solvers:
    #- http01:
    #    ingress:
    #      class:  nginx
    - dns01:
        cloudflare:
          email: dylan@incidentcad.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - 'incidentcad.com'
        - '*.incidentcad.com'